
language: python

  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
cache:
  directories:
    - $HOME/.wheelhouse/
env:
  global:
    - TRAVIS_CACHE=$HOME/.travis_cache/
    - TRAVIS_NODE_VERSION="5.11"
  matrix:
    #- TOX_ENV=py27-mysql
    - TOX_ENV=py27-sqlite
    - TOX_ENV=py27-postgres
    - TOX_ENV=py34-sqlite
    - TOX_ENV=py34-mysql
    - TOX_ENV=py34-postgres
    - TOX_ENV=javascript
before_install:
  - npm install -g npm@'>=3.9.5'
before_script:
  - mysql -e 'drop database if exists caravel; create database caravel DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci' -u root
  - psql -c 'create database caravel;' -U postgres
  - export PATH=${PATH}:/tmp/hive/bin
install:
  - pip install --upgrade pip
  - pip install tox tox-travis
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
script: tox -e $TOX_ENV

# test
